---
- hosts: web
  vars:
    http_port: 80
    max_clients: 700
  remote_user: ec2-user
  sudo_user: root 
  sudo: yes
  tasks:
  #- name: disable selinux
  #  command: /usr/sbin/setenforce 0
  - name: yum update 
    yum: name=* state=latest
  - name: install epel 
    yum: pkg=epel-release state=latest
  - name: add zend repository 
    template: src=zend/zend.repo dest=/etc/yum.repos.d/zend.repo
  - name: install httpd 
    yum: pkg=httpd state=latest
  - name: mkdir /etc/httpd/vhosts.d
    file: path=/etc/httpd/vhosts.d state=directory 
  - name: urbania configuration httpd
    template: src=httpd/urbania.conf dest=/etc/httpd/vhosts.d/urbania.conf
  - name: add port 8080 
    lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " insertafter="^#Listen " line="Listen 8080"
  - name: add vhosts
    #lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen " insertafter="^Include conf.d" line="Include vhosts.d/*.conf"
    lineinfile: dest=/etc/httpd/conf/httpd.conf insertafter="^Include conf.d" line="Include vhosts.d/*.conf"
  - name: install policycoreutils 
    yum: pkg=policycoreutils-python state=latest
  - name: install zend-server-common 
    yum: name=http://repos-source.zend.com/zend-server/6.2/rpm/x86_64/zend-server-php-5.4-common-6.2.0-2002.x86_64.rpm
  - name: install zend-server
    #yum: pkg=zend-server-php-5.4 enablerepo=epel state=latest
    #yum: name=http://repos-source.zend.com/zend-server/6.2/rpm/x86_64/zend-server-php-5.4-6.2.0-2002.x86_64.rpm 
    command:  rpm -Uvh --replacefiles http://repos-source.zend.com/zend-server/6.2/rpm/x86_64/zend-server-php-5.4-6.2.0-2002.x86_64.rpm  http://repos-source.zend.com/zend-server/6.2/rpm/x86_64/mod-php-5.4-apache2-zend-server-5.4.21-20.x86_64.rpm 
  #- name: install zend-server-modphp
  #  yum: name=http://repos-source.zend.com/zend-server/6.2/rpm/x86_64/mod-php-5.4-apache2-zend-server-5.4.21-20.x86_64.rpm
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: install devel components 
    yum: pkg=make,gcc,php-5.4-dev-zend-server,git,autoconf state=latest
  - name: clone phalcon
    command: "{{ item }} chdir=/opt/"
    with_items:
    - git clone git://github.com/phalcon/cphalcon.git 
  - name: get phalcon 1.3.3
    command: "{{ item }} chdir=/opt/cphalcon"
    with_items:
    - git fetch
    - git checkout 1.3.3 
  - name: install phalcon 1.3.3
    command: "{{ item }} chdir=/opt/cphalcon/build"
    with_items:
    - /opt/cphalcon/build/install
    environment:
      PATH: /usr/local/zend/bin:{{ ansible_env.PATH }}
  - name: phalcon ini file 
    template: src=phalcon/phalcon.ini dest=/usr/local/zend/etc/conf.d/phalcon.ini
    notify:
    - restart apache
  - name: Add deployment user
    action: user name=websync
  - name: mkdir /apps/urbania 
    file: path=/apps/urbania state=directory owner=websync
  - name: set keys
    authorized_key: user=websync
                    key="{{ item }}"
    with_file:
     - keys/websync.pub
  #- name: execute composer (after deployment) 
  #  command: "{{ item }} chdir=/apps/urbania/api.urbania.pe"
  #  with_items:
  #  - /usr/local/zend/bin/php composer.phar update 
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
