---
# file: roles/cdh_zookeeper_server/tasks/main.yml

- name: install zookeeper-server via yum
  yum: name={{ item }} state=latest
  with_items:
    - zookeeper
    - zookeeper-server
  tags: zookeeper

- name: copy /etc/zookeeper/conf.dist to /etc/zookeeper/conf
  command: creates=/etc/zookeeper/conf cp -R -p /etc/zookeeper/conf.dist /etc/zookeeper/conf
  tags: zookeeper

- name: create /var/lib/zookeeper directory
  file: path=/var/lib/zookeeper owner=zookeeper group=zookeeper state=directory
  tags: zookeeper

- name: configure ZooKeeper in /etc/zookeeper/conf
  template: src=zoo.cfg dest=/etc/zookeeper/conf/zoo.cfg owner=zookeeper group=zookeeper mode=0644
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: initialize ZooKeeper
  command: creates=/var/lib/zookeeper/myid service zookeeper-server init --myid={{ zookeeper_id }}
  tags: zookeeper
