- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
  - create-instance
- hosts: tag_Service_nagios  
  gather_facts: true
  remote_user: ec2-user
  sudo_user: root
  sudo: yes
  roles :
  - base
  - nagios
  - plugins
  - nrpe
  - pnp4
  - check-mk

