  - name: ec2 group VP4-S05-N01
    ec2_group:
     name: VP4-S05-N01
     description: Prod:Nagios:Infraestructura
     vpc_id: vpc-5d704e38
     region: us-east-1
     rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 190.117.227.245/32
      - proto: tcp
        from_port: 5666 
        to_port: 5666
        cidr_ip: 30.0.0.0/16
        from_port: 22
        to_port: 22
        cidr_ip: 190.117.227.245/32
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 190.117.227.245/32
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 190.235.133.208/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 190.235.133.208/32
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 190.235.133.208/32
  - name: run instance
    ec2:
     key_name: VP4-S05-N01
     instance_type: t2.small
     image: ami-0d4cfd66
     wait: yes
     group: VP4-S05-N01
     wait_timeout: 500
     count: 1
     vpc_subnet_id: subnet-c0673999
     instance_tags:
       Name: VP4-S05-N01
       Service: nagios
       Alias: v4s5n1
       Env: producion
       Product: infraestructura 
     region: us-east-1
     volumes:
       - device_name: /dev/xvda
         volume_size: 50
       - device_name: /dev/xvdh
         volume_size: 20
       - device_name: /dev/xvdf
         volume_size: 100
    tags: run-instances
  - name: waiting for server to come back
    local_action: wait_for host=tag_service_nagios state=started
    sudo: false
  - name: Wait for checks
    pause: seconds=120
