---
# file: roles/nginx/tasks/main.yml

- name: Install php via yum
  yum: name={{ item }} state=installed
  with_items:
    - php-fpm
    - php-pecl-apc
    - php-common
    - php-gd
    - php-devel
    - php
    - php-mbstring
    - php-pear-Mail
    - php-cli
    - php-imap
    - php-snmp
    - php-pdo
    - php-xml
  tags:
    - monitor
    - ganglia
  when: with_ganglia

- name: Install Nginx repo
  shell: rpm -Uvh http://nginx.org/packages/centos/6/x86_64/RPMS/nginx-1.6.2-1.el6.ngx.x86_64.rpm
  ignore_errors: yes
  tags:
    - monitor
    - ganglia
  when: with_ganglia

- name: Install nginx
  yum: name=nginx state=latest
  tags:
    - monitor
    - ganglia
  when: with_ganglia

- name: copy nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags:
    - monitor
    - ganglia
  when: with_ganglia

- name: copy default
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  tags:
    - monitor
    - ganglia
  when: with_ganglia

- name: start php-fpm
  service: name=php-fpm enabled=yes state=started
  tags:
    - monitor
    - ganglia
  when: with_ganglia

- name: start nginx
  service: name=nginx enabled=yes state=started
  tags:
    - monitor
    - ganglia
  when: with_ganglia
